--db schema
CREATE TABLE users (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_NAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL,
    ACTIVE VARCHAR(1) NOT NULL DEFAULT 'Y',
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED TIMESTAMP
);

--triger
CREATE TRIGGER USERS_UPDATE AFTER UPDATE ON USERS
    WHEN OLD.PASSWORD <> NEW.PASSWORD
    OR OLD.USER_NAME <> NEW.USER_NAME
    OR OLD.ACTIVE <> NEW.ACTIVE
BEGIN
    UPDATE USERS SET MODIFIED = CURRENT_TIMESTAMP WHERE ID = OLD.ID;
END;

drop table activity_log;
CREATE TABLE activity_log (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ADMIN_USER_NAME varchar(50) NOT NULL,
    USER_NAME VARCHAR(50) NOT NULL,
    TICKET VARCHAR(10) NOT NULL,
    ACTIVITY_TYPE VARCHAR(50) NOT NULL,
    CMD VARCHAR(200) NOT NULL,
    STATUS VARCHAR(50),
    OUTPUT VARCHAR(500),
    ERROR VARCHAR(500),
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED TIMESTAMP
);
